- alias: "Set Volume"
  trigger:
    - platform: state
      entity_id: input_slider.Keuken
  action:
    - service: media_player.volume_set
      data_template:
       entity_id: media_player.keuken
       volume_level: >
          {{states.input_slider.keuken.state | int / 100}}
